version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: scrabble-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

  scrabble:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrabble-be
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/scrabble
      - ALLOWED_HOSTS=http://localhost:3001
    volumes:
      - .:/app
    networks:
      - mongodb_network

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge